# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabs = QtWidgets.QTabWidget(self.splitter)
        self.tabs.setObjectName("tabs")
        self.tab_sig = QtWidgets.QWidget()
        self.tab_sig.setObjectName("tab_sig")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_sig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sigs = TreeView(self.tab_sig)
        self.sigs.setObjectName("sigs")
        self.verticalLayout.addWidget(self.sigs)
        self.tabs.addTab(self.tab_sig, "")
        self.tab_pre = QtWidgets.QWidget()
        self.tab_pre.setObjectName("tab_pre")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_pre)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.thumbs = ThumbList(self.tab_pre)
        self.thumbs.setObjectName("thumbs")
        self.verticalLayout_2.addWidget(self.thumbs)
        self.tabs.addTab(self.tab_pre, "")
        self.pdfView = PdfViewer(self.splitter)
        self.pdfView.setObjectName("pdfView")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSignatures = QtWidgets.QMenu(self.menubar)
        self.menuSignatures.setObjectName("menuSignatures")
        self.menuDokument = QtWidgets.QMenu(self.menubar)
        self.menuDokument.setObjectName("menuDokument")
        self.menuCertifivates = QtWidgets.QMenu(self.menubar)
        self.menuCertifivates.setObjectName("menuCertifivates")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionPrint_setup = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-print-preview")
        self.actionPrint_setup.setIcon(icon)
        self.actionPrint_setup.setObjectName("actionPrint_setup")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-print")
        self.actionPrint.setIcon(icon)
        self.actionPrint.setObjectName("actionPrint")
        self.actionDocument_Info = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionDocument_Info.setIcon(icon)
        self.actionDocument_Info.setObjectName("actionDocument_Info")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSelect_all = QtWidgets.QAction(MainWindow)
        self.actionSelect_all.setObjectName("actionSelect_all")
        self.actionSign = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./../cannibal/icons/sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSign.setIcon(icon)
        self.actionSign.setObjectName("actionSign")
        self.actionSign_invisibly = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSign_invisibly.setIcon(icon1)
        self.actionSign_invisibly.setObjectName("actionSign_invisibly")
        self.actionInsert_text = QtWidgets.QAction(MainWindow)
        self.actionInsert_text.setIcon(icon1)
        self.actionInsert_text.setObjectName("actionInsert_text")
        self.actionInsert_image = QtWidgets.QAction(MainWindow)
        self.actionInsert_image.setObjectName("actionInsert_image")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionZoom_original = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-original")
        self.actionZoom_original.setIcon(icon)
        self.actionZoom_original.setObjectName("actionZoom_original")
        self.actionZoom_fit_best = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-fit-best")
        self.actionZoom_fit_best.setIcon(icon)
        self.actionZoom_fit_best.setObjectName("actionZoom_fit_best")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-in")
        self.actionZoom_in.setIcon(icon)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.actionZoom_out.setIcon(icon)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionFirst_page = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-first")
        self.actionFirst_page.setIcon(icon)
        self.actionFirst_page.setObjectName("actionFirst_page")
        self.actionPrevious_page = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.actionPrevious_page.setIcon(icon)
        self.actionPrevious_page.setObjectName("actionPrevious_page")
        self.actionNext_page = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.actionNext_page.setIcon(icon)
        self.actionNext_page.setObjectName("actionNext_page")
        self.actionLast_page = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-last")
        self.actionLast_page.setIcon(icon)
        self.actionLast_page.setObjectName("actionLast_page")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionManage_certificate = QtWidgets.QAction(MainWindow)
        self.actionManage_certificate.setObjectName("actionManage_certificate")
        self.actionRotate_left = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("object-rotate-left")
        self.actionRotate_left.setIcon(icon)
        self.actionRotate_left.setObjectName("actionRotate_left")
        self.actionRotate_right = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("object-rotate-right")
        self.actionRotate_right.setIcon(icon)
        self.actionRotate_right.setObjectName("actionRotate_right")
        self.actionDelete_page = QtWidgets.QAction(MainWindow)
        self.actionDelete_page.setObjectName("actionDelete_page")
        self.actionInsert_page = QtWidgets.QAction(MainWindow)
        self.actionInsert_page.setObjectName("actionInsert_page")
        self.actionAppend_page = QtWidgets.QAction(MainWindow)
        self.actionAppend_page.setObjectName("actionAppend_page")
        self.actionInsert_stamp = QtWidgets.QAction(MainWindow)
        self.actionInsert_stamp.setObjectName("actionInsert_stamp")
        self.actionInsert_form = QtWidgets.QAction(MainWindow)
        self.actionInsert_form.setObjectName("actionInsert_form")
        self.actionInsert_document = QtWidgets.QAction(MainWindow)
        self.actionInsert_document.setObjectName("actionInsert_document")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint_setup)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDocument_Info)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuView.addAction(self.actionZoom_original)
        self.menuView.addAction(self.actionZoom_fit_best)
        self.menuView.addSeparator()
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuSignatures.addAction(self.actionInsert_text)
        self.menuSignatures.addAction(self.actionInsert_image)
        self.menuSignatures.addAction(self.actionInsert_stamp)
        self.menuSignatures.addAction(self.actionInsert_form)
        self.menuSignatures.addSeparator()
        self.menuSignatures.addAction(self.actionSign)
        self.menuSignatures.addAction(self.actionSign_invisibly)
        self.menuDokument.addAction(self.actionFirst_page)
        self.menuDokument.addAction(self.actionPrevious_page)
        self.menuDokument.addAction(self.actionNext_page)
        self.menuDokument.addAction(self.actionLast_page)
        self.menuDokument.addSeparator()
        self.menuDokument.addAction(self.actionRotate_left)
        self.menuDokument.addAction(self.actionRotate_right)
        self.menuDokument.addSeparator()
        self.menuDokument.addAction(self.actionFind)
        self.menuDokument.addSeparator()
        self.menuDokument.addAction(self.actionDelete_page)
        self.menuDokument.addAction(self.actionInsert_page)
        self.menuDokument.addAction(self.actionAppend_page)
        self.menuDokument.addSeparator()
        self.menuDokument.addAction(self.actionInsert_document)
        self.menuCertifivates.addAction(self.actionManage_certificate)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSignatures.menuAction())
        self.menubar.addAction(self.menuDokument.menuAction())
        self.menubar.addAction(self.menuCertifivates.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSign)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFirst_page)
        self.toolBar.addAction(self.actionPrevious_page)
        self.toolBar.addAction(self.actionNext_page)
        self.toolBar.addAction(self.actionLast_page)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_original)
        self.toolBar.addAction(self.actionZoom_fit_best)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRotate_left)
        self.toolBar.addAction(self.actionRotate_right)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cannibal"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_sig), _translate("MainWindow", "Signatures"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_pre), _translate("MainWindow", "Pages"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuSignatures.setTitle(_translate("MainWindow", "&Signatures"))
        self.menuDokument.setTitle(_translate("MainWindow", "&Document"))
        self.menuCertifivates.setTitle(_translate("MainWindow", "&Certificates"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "&Close"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save &as..."))
        self.actionPrint_setup.setText(_translate("MainWindow", "Print set&up..."))
        self.actionPrint.setText(_translate("MainWindow", "&Print..."))
        self.actionDocument_Info.setText(_translate("MainWindow", "&Document properties"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSelect_all.setText(_translate("MainWindow", "&Delete page"))
        self.actionSign.setText(_translate("MainWindow", "&Sign with form..."))
        self.actionSign_invisibly.setText(_translate("MainWindow", "S&ign..."))
        self.actionInsert_text.setText(_translate("MainWindow", "Insert &text..."))
        self.actionInsert_image.setText(_translate("MainWindow", "Insert &image..."))
        self.actionMinimize.setText(_translate("MainWindow", "&Minimize"))
        self.actionHelp.setText(_translate("MainWindow", "&Help"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionZoom_original.setText(_translate("MainWindow", "Zoom original"))
        self.actionZoom_original.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.actionZoom_fit_best.setText(_translate("MainWindow", "Zoom fit best"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_in.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionZoom_out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionFirst_page.setText(_translate("MainWindow", "&First page"))
        self.actionFirst_page.setShortcut(_translate("MainWindow", "Ctrl+Home"))
        self.actionPrevious_page.setText(_translate("MainWindow", "&Previous page"))
        self.actionPrevious_page.setShortcut(_translate("MainWindow", "PgUp"))
        self.actionNext_page.setText(_translate("MainWindow", "&Next page"))
        self.actionNext_page.setShortcut(_translate("MainWindow", "PgDown"))
        self.actionLast_page.setText(_translate("MainWindow", "L&ast page"))
        self.actionLast_page.setShortcut(_translate("MainWindow", "Ctrl+End"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionManage_certificate.setText(_translate("MainWindow", "&Manage certificates..."))
        self.actionRotate_left.setText(_translate("MainWindow", "Rotate &left"))
        self.actionRotate_left.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionRotate_right.setText(_translate("MainWindow", "Rotate &right"))
        self.actionRotate_right.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionDelete_page.setText(_translate("MainWindow", "&Delete page"))
        self.actionDelete_page.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.actionInsert_page.setText(_translate("MainWindow", "&Insert page"))
        self.actionInsert_page.setShortcut(_translate("MainWindow", "Ctrl+Ins"))
        self.actionAppend_page.setText(_translate("MainWindow", "&Append page"))
        self.actionInsert_stamp.setText(_translate("MainWindow", "Insert s&tamp..."))
        self.actionInsert_form.setText(_translate("MainWindow", "Insert &form..."))
        self.actionInsert_document.setText(_translate("MainWindow", "Insert &document..."))
        self.actionNew.setText(_translate("MainWindow", "&New"))
from QtPdfViewer import PdfViewer, ThumbList
from treeview import TreeView
